//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub mod prelude;

pub mod knowledge;
pub mod knowledge_tag;
pub mod problem;
pub mod problem_tag;
pub mod submission;
pub mod tag;
pub mod user;
