//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::ai_analysis::Entity as AiAnalysis;
pub use super::knowledge::Entity as Knowledge;
pub use super::knowledge_tag::Entity as KnowledgeTag;
pub use super::problem::Entity as Problem;
pub use super::problem_tag::Entity as ProblemTag;
pub use super::submission::Entity as Submission;
pub use super::tag::Entity as Tag;
pub use super::task::Entity as Task;
pub use super::template::Entity as Template;
pub use super::template_problem::Entity as TemplateProblem;
pub use super::template_tag::Entity as TemplateTag;
pub use super::user::Entity as User;
