//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::knowledge::Entity as Knowledge;
pub use super::knowledge_tag::Entity as KnowledgeTag;
pub use super::problem::Entity as Problem;
pub use super::problem_tag::Entity as ProblemTag;
pub use super::submission::Entity as Submission;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
