//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "problem")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub source: String,
    pub external_id: Option<String>,
    pub title: String,
    pub url: Option<String>,
    pub difficulty: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub statement: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::knowledge::Entity")]
    Knowledge,
    #[sea_orm(has_many = "super::problem_tag::Entity")]
    ProblemTag,
    #[sea_orm(has_many = "super::submission::Entity")]
    Submission,
    #[sea_orm(has_many = "super::template::Entity")]
    Template,
    #[sea_orm(has_many = "super::template_problem::Entity")]
    TemplateProblem,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::knowledge::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Knowledge.def()
    }
}

impl Related<super::problem_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProblemTag.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl Related<super::template_problem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateProblem.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::problem_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::problem_tag::Relation::Problem.def().rev())
    }
}

impl Related<super::template::Entity> for Entity {
    fn to() -> RelationDef {
        super::template_problem::Relation::Template.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::template_problem::Relation::Problem.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
