//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::knowledge_tag::Entity")]
    KnowledgeTag,
    #[sea_orm(has_many = "super::problem_tag::Entity")]
    ProblemTag,
    #[sea_orm(has_many = "super::template_tag::Entity")]
    TemplateTag,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::knowledge_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KnowledgeTag.def()
    }
}

impl Related<super::problem_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProblemTag.def()
    }
}

impl Related<super::template_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateTag.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::knowledge::Entity> for Entity {
    fn to() -> RelationDef {
        super::knowledge_tag::Relation::Knowledge.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::knowledge_tag::Relation::Tag.def().rev())
    }
}

impl Related<super::problem::Entity> for Entity {
    fn to() -> RelationDef {
        super::problem_tag::Relation::Problem.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::problem_tag::Relation::Tag.def().rev())
    }
}

impl Related<super::template::Entity> for Entity {
    fn to() -> RelationDef {
        super::template_tag::Relation::Template.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::template_tag::Relation::Tag.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
