//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "template")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub title: String,
    pub category: String,
    pub language: String,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub time_complexity: Option<String>,
    pub space_complexity: Option<String>,
    pub source: String,
    pub source_problem_id: Option<i64>,
    pub difficulty: Option<i32>,
    pub usage_count: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub summary: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::problem::Entity",
        from = "Column::SourceProblemId",
        to = "super::problem::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Problem,
    #[sea_orm(has_many = "super::template_problem::Entity")]
    TemplateProblem,
    #[sea_orm(has_many = "super::template_tag::Entity")]
    TemplateTag,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::template_problem::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateProblem.def()
    }
}

impl Related<super::template_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TemplateTag.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::problem::Entity> for Entity {
    fn to() -> RelationDef {
        super::template_problem::Relation::Problem.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::template_problem::Relation::Template.def().rev())
    }
}

impl Related<super::tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::template_tag::Relation::Tag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::template_tag::Relation::Template.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
